### ISSUE TITLE
Empty words left in $CityRPG::temp::spawnpoints

### ISSUE THREAD

**Issue by Dglider** [cityrpg/Blockland-CityRPG-4#13]
on line 182 of server/core.cs
`$CityRPG::temp::spawnPoints = strreplace($CityRPG::temp::spawnPoints, %brick, "");`

This will leave blank words in the spawnPoint list.
A proper replacement would use the [removeWord function](http://docs.garagegames.com/tge/official/content/documentation/Reference/Console%20Functions/TorqueScript_Console_Functions_3.html#removeWord.28_sourceString_.2Cindex.29).
```
$CityRPG::temp::spawnPoints = removeWord($CityRPG::temp::spawnPoints, %a);
%a--;
```

I wouldn't normally submit this as a bug, but I want to make sure this sort of mistake isn't repeated in the future.  It's like... data littering.

**Comment by Dglider** [comment]
This still bugs me.

**Comment by LakeYS** [comment]
Fixed finally. Sorry for the huge delays.
