### ISSUE TITLE
extra cash dumped into the economy disappears into the ether

### ISSUE THREAD

**Issue by Dglider** [cityrpg/Blockland-CityRPG-4#17]
heheh.  Lotus dumped 10k into the economy, but it's capped at 150.
It could be modified to refuse the extra money.

Question is, should it?  Or is that a lesson people should learn?

**Comment by LakeYS** [comment]
Extra cash definitely should not disappear. I would prefer to block users from donating any amount that would push the value past 150%.

There is already a check for donating excessive amounts, but it's only triggered if the economy is at max value. See commands.cs, line 178.

**Comment by Dglider** [comment]
It looks like someone capped the total donation amount but they don't take into account the current economy.  Laaaame.

Replace these lines (187 - 189)
```
		if(%arg1*0.15 >= $Pref::Server::City::Economics::Cap) {
			%arg1 = mCeil($Pref::Server::City::Economics::Cap*6.6666667);
		}
```

With this
```
if(%arg1*0.15+$Economics::Condition > $Pref::Server::City::Economics::Cap) {
	%arg1 = mFloor(($Pref::Server::City::Economics::Cap-$Economics::Condition)/0.15);
}
```
If current donation goes over cap, set donation amount to cap minus economy condition
