### ISSUE TITLE
Clients do not get any money from food sold while offline.

### ISSUE THREAD

**Issue by Dglider** [cityrpg/Blockland-CityRPG-4#28]
https://github.com/cityrpg/Blockland-CityRPG-4/blob/3fea7e8e1c8b39b82d7d2a67f915f44747060c97/GameMode_CityRPG4/server/player.cs#L388

We should either, not charge the profit fee, or give the selling player the money even when they are offline.

**Comment by LakeYS** [comment]
Yikes, fixing this right away.
