### ISSUE TITLE
deleting a service offering brick can get people stuck unable to refuse the previous offer

### ISSUE THREAD

**Issue by Dglider** [cityrpg/Blockland-CityRPG-4#29]
If I click a sellFood brick, then that brick is deleted, I can not accept other offers.
If I suicide it fixes itself.
If I say /yes it fixes itself.

![image](https://user-images.githubusercontent.com/47409327/73996780-d1238f00-4919-11ea-87ec-8578dfe8293f.png)

I would suggest that /no cancel the previous offer if the offering brick doesn't exist.

**Comment by LakeYS** [comment]
I think an easy fix would be to change the isObject check to a blank string check (commands.cs, line 186).

Note, the upcoming update is planned to phase out the /yes and /no command format anyway.

**Comment by LakeYS** [comment]
Fixed, thanks for the report.
