### ISSUE TITLE
Lots are removed when loaded through the autosaver

### ISSUE THREAD

**Issue by LakeYS** [cityrpg/Blockland-CityRPG-4#5]
Only able to replicate on a dedicated server.

**Comment by Dglider** [comment]
It must be performing the CityRPG_OnPlant function with no client present.  So it would automatically fail all checks and delete the brick.
The duplicator emulates brick loading when it plants bricks.  So make sure to test against that when you fix this.

**Comment by LakeYS** [comment]
That is what I'm thinking, but I have still yet to consistently reproduce the problem. What I'll likely do is add a check on lot removal for if there are bricks loading, and if true, drop an error dumping relevant information. The error will be benign if a player is actually attempting to plant a lot during loading.

**Comment by LakeYS** [comment]
Even under conditions seemingly identical to the original repro, I am no-longer able to reproduce this. I have added the warning in 37a58c7, which also dumps data. If there are any occurrences, the dump should be sufficient to trace a cause. An override for brick planting has been set up in 01a7870 to prevent players from creating false positives.

It is highly likely that the best approach to fix this will end up being a rewrite of City_OnPlant with better fault handling for loading bricks. See here: https://trello.com/c/Yrddn5KZ/73-onplant-refactor-part-2

**Comment by LakeYS** [comment]
Once again occurring on the main server, the "dump" simply nets an error, meaning the brick deletion is happening somewhere earlier up the line than anticipated.
```
Add-Ons/GameMode_CityRPG4/server/package.cs (502): Unable to find object: '' att
empting to call function 'dump'
BackTrace: ->ServerLoadSaveFile_Tick->[happyDoorFunTime]fxDTSBrick::onLoadPlant-
>[CityRPG_MainPackage]fxDTSBrick::onLoadPlant
```

**Comment by LakeYS** [comment]
I just realized the mistake I made here is calling `dump` on a brick after it has already been deleted, hence the status triggering the error in the first place. The schedules on the "delete" calls did not prevent this.

Since the problem clearly lies in the rat's nest itself, City_OnPlant, I'm going to go forward with rewriting this function outright. There's simply no use trying to debug it.

**Comment by LakeYS** [comment]
Thanks @Dglider for the fix. I'm still going to continue rewriting the onPlant functionality, but this at least fixes lots loading for now.
