### ISSUE TITLE
Players do not spawn in spawn bricks while they are being built

### ISSUE THREAD

**Issue by LakeYS** [cityrpg/Blockland-CityRPG-4#8]

**Comment by Dglider** [comment]
I spotted this in the code yesterday. It's just 1 line that needs to be removed.
The spawn list should not be cleared before starting the build process.

Also, why aren't we just hooking spawn brick placement and deletion, and maintaining the spawn list that way?  onPlant, onLoadPlant, and onRemove are all valid hooks for these bricks. :?
